branches:
  only:
    - master

language: node_js

sudo: false

node_js:
  - '8'

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:

script:
  - npm run build

after_success:
 - cd dist
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update docs"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle
