/**
 * Created by my9074 on 2017/3/21.
 */
export const FETCH_MOVIES = 'FETCH_MOVIES'
export const FETCH_MOVIES_IN_THEATERS = 'FETCH_MOVIES_IN_THEATERS'
export const FETCH_MOVIES_COMING_SOON = 'FETCH_MOVIES_COMING_SOON'
export const CLEAR_MOVIES = 'CLEAR_MOVIES'
